### ISSUE TITLE
Text in brackets from lyrics is not removed

### ISSUE THREAD

**Issue by maelchiotti** [aaronhktan/lyric-grabber#4]
Lyrics from Genius always have the parts of the song in brackets, anf sometimes the artists. I see there is an option in Quaver to automatically remove them, but it doesn't seem to work for me.

**Comment by aaronhktan** [comment]
Hey @maelchiotti!

The option you see might be "Remove parts of song title and artist in brackets when searching for lyrics". This does not remove the items in brackets in the lyrics. Rather, it configures the program to ignore words in brackets when searching for a song title or artist.

For example, a song title might be "La Traversée (de l’Atlantique en 1774)". If the option is enabled, Quaver will search for a song called "La Traversée", instead of "La Traversée (de l’Atlantique en 1774)".

Anyway, thanks for opening this issue, and have a great day!

**Comment by maelchiotti** [comment]
Oh right, I understand! Thanks for explaining it.
I still think a feature to remove text in brackets in the lyrics would be
very useful!

Keep up the great work and have a great day too!
